<<<<<<< HEAD
# Generated by Django 4.2.4 on 2023-09-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshot',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
=======
# Generated by Django 4.2.4 on 2023-09-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshot',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
>>>>>>> f2fd8dd9ad99e6bd9ed1bbd2528dfbd546f05c95
