# Generated by Django 4.2.4 on 2023-09-14 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_snapshot_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshot',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
